# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/pelican
image: apihackers/pelican:latest

stages:
  - build
  - publish
  
# pages_job:
#   tags:
#     - docker
#   stage: build
#   script:
#     - pelican content
#     - echo "test"
#   artifacts:
#     paths:
#       - public/

# image: python:2.7-alpine

build_job:
  stage: build
  tags:
    - docker
  script:
    - pelican -s pelicanconf.py
  artifacts:
    paths:
      - output/
      
publish_job:
  stage: publish
  tags:
    - docker
  script:
    - pip3 install ghp-import
    - make github
